<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */
?>


<div class="col-m-12">
    <div class="shortcuts">
        <h2 class="title">Principais Atalhos:</h2>
        <div class="items dados">
            <a href="<?php echo $block->getUrl('admin/system_config/index'); ?>">
                <div class="item dados">
                    <span>Dados da <br> Loja</span>
                </div>
            </a>
            <a href="<?php echo $block->getUrl('theme/design_config/edit/scope/stores/scope_id/1'); ?>">
                <div class="item logotipo">
                    <span>Editar <br> Logotipo</span>
                </div>
            </a>
            <a href="#">
                <div class="item cores">
                    <span>Cores do <br> Layout</span>
                </div>
            </a>
            <a href="<?php echo $block->getUrl('admin/system_config/edit/section/payment'); ?>">
                <div class="item pagamento">
                    <span>Formas de <br> Pagamento</span>
                </div>
            </a>
            <a href="<?php echo $block->getUrl('admin/system_config/edit/section/carriers'); ?>">
                <div class="item entrega">
                    <span>Formas de <br> Entrega</span>
                </div>
            </a>
        </div>
    </div>
</div>

<div class="dashboard-container row">
    <div class="dashboard-main col-m-8 col-m-push-4">
        <div class="dashboard-diagram-container">
            <?= $block->getChildHtml('chartDisabled') ?>
            <?= $block->getChildHtml('diagrams') ?>
            <?php
                $diagramsBlock = $block->getChildBlock('diagrams');
                $tabsIds = $diagramsBlock ? $diagramsBlock->getTabsIds() : [];
            ?>
            <?php if (is_array($tabsIds)): ?>
                <?= $block->getChildHtml('diagramsPeriod') ?>
                <div id="diagram_tab_content" class="dashboard-diagram-tab-content"></div>
            <?php endif; ?>
        </div>
        <?= $block->getChildHtml('totals') ?>
        <div class="dashboard-store-stats">
            <?= $block->getChildHtml('grids') ?>
            <div id="grid_tab_content" class="dashboard-store-stats-content"></div>
            <?= $block->getChildHtml('refresh_statistics') ?>
        </div>
    </div>
    <div class="dashboard-secondary col-m-4 col-m-pull-8">
        <?= $block->getChildHtml('sales') ?>
        <div class="dashboard-item">
            <div class="dashboard-item-title"><?= $block->escapeHtml(__('Last Orders')) ?></div>
            <?= $block->getChildHtml('lastOrders') ?>
        </div>
        <div class="dashboard-item">
            <div class="dashboard-item-title"><?= $block->escapeHtml(__('Last Search Terms')) ?></div>
            <?= $block->getChildHtml('lastSearches') ?>
        </div>
        <div class="dashboard-item">
            <div class="dashboard-item-title"><?= $block->escapeHtml(__('Top Search Terms')) ?></div>
            <?= $block->getChildHtml('topSearches') ?>
        </div>
    </div>
</div>
